### ISSUE TITLE
Improve facets admin UI view

### ISSUE THREAD

**Issue by andybroomfield** [localgovdrupal/localgov_directories#289]
Following on from facet improvements, I found it quite difficult in Localgov Drupal.
We've got a custom view in BHCC, would this be of interest?

<img width="1156" alt="Screenshot 2023-05-24 at 4 01 30 pm" src="https://github.com/localgovdrupal/localgov_directories/assets/1467480/1cfcc231-8868-4928-967d-0c4f85f6ca55">

**Comment by andybroomfield** [comment]
I could add this if there is any interest.
Heres the view yaml from BHCC
```yaml
langcode: en
status: true
dependencies:
  module:
    - localgov_directories
    - user
    - views_bulk_operations
id: bhcc_facet_manager
label: 'Facet manager'
module: views
description: ''
tag: ''
base_table: localgov_directories_facets_field_data
base_field: id
display:
  default:
    id: default
    display_title: Default
    display_plugin: default
    position: 0
    display_options:
      title: 'Directory and event facets'
      fields:
        views_bulk_operations_bulk_form:
          id: views_bulk_operations_bulk_form
          table: views
          field: views_bulk_operations_bulk_form
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: views_bulk_operations_bulk_form
          label: 'Views bulk operations'
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          batch: true
          batch_size: 10
          form_step: true
          ajax_loader: false
          buttons: false
          action_title: Action
          clear_on_exposed: true
          force_selection_info: false
          selected_actions:
            1:
              action_id: views_bulk_operations_delete_entity
              preconfiguration:
                label_override: 'Delete facet'
        title:
          id: title
          table: localgov_directories_facets_field_data
          field: title
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: null
          entity_field: title
          plugin_id: field
          label: Name
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: string
          settings:
            link_to_entity: false
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
        bundle:
          id: bundle
          table: localgov_directories_facets_field_data
          field: bundle
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: localgov_directories_facets
          entity_field: bundle
          plugin_id: field
          label: 'Directory Facets type'
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: target_id
          type: entity_reference_label
          settings:
            link: true
          group_column: target_id
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
        operations:
          id: operations
          table: localgov_directories_facets
          field: operations
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: localgov_directories_facets
          plugin_id: entity_operations
          label: 'Operations links'
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          destination: false
      pager:
        type: full
        options:
          offset: 0
          items_per_page: 50
          total_pages: null
          id: 0
          tags:
            next: ››
            previous: ‹‹
            first: '« First'
            last: 'Last »'
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 25, 50'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
          quantity: 9
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      access:
        type: perm
        options:
          perm: 'access directory facets overview'
      cache:
        type: tag
        options: {  }
      empty: {  }
      sorts:
        weight:
          id: weight
          table: localgov_directories_facets_field_data
          field: weight
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: localgov_directories_facets
          entity_field: weight
          plugin_id: standard
          order: DESC
          expose:
            label: ''
            field_identifier: ''
          exposed: false
        bundle:
          id: bundle
          table: localgov_directories_facets_field_data
          field: bundle
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: localgov_directories_facets
          entity_field: bundle
          plugin_id: standard
          order: ASC
          expose:
            label: ''
            field_identifier: ''
          exposed: false
        title:
          id: title
          table: localgov_directories_facets_field_data
          field: title
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: localgov_directories_facets
          entity_field: title
          plugin_id: standard
          order: ASC
          expose:
            label: ''
            field_identifier: ''
          exposed: false
      arguments: {  }
      filters:
        title:
          id: title
          table: localgov_directories_facets_field_data
          field: title
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: localgov_directories_facets
          entity_field: title
          plugin_id: string
          operator: contains
          value: ''
          group: 1
          exposed: true
          expose:
            operator_id: title_op
            label: Name
            description: ''
            use_operator: false
            operator: title_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: title
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              emergency_publisher: '0'
              inquest_editor: '0'
              anonymous: '0'
              localgov_editor: '0'
              tro_editor: '0'
              localgov_author: '0'
              localgov_contributor: '0'
              localgov_news_editor: '0'
              localgov_user_manager: '0'
              directory_editor: '0'
              event_editor: '0'
              technical_admin: '0'
              webform_editor: '0'
            placeholder: ''
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
        bundle:
          id: bundle
          table: localgov_directories_facets_field_data
          field: bundle
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: localgov_directories_facets
          entity_field: bundle
          plugin_id: bundle
          operator: in
          value: {  }
          group: 1
          exposed: true
          expose:
            operator_id: bundle_op
            label: 'Directory Facets type'
            description: ''
            use_operator: false
            operator: bundle_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: bundle
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              emergency_publisher: '0'
              inquest_editor: '0'
              anonymous: '0'
              localgov_editor: '0'
              tro_editor: '0'
              localgov_author: '0'
              localgov_contributor: '0'
              localgov_news_editor: '0'
              localgov_user_manager: '0'
              directory_editor: '0'
              event_editor: '0'
              technical_admin: '0'
              webform_editor: '0'
            reduce: false
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
      filter_groups:
        operator: AND
        groups:
          1: AND
      style:
        type: table
        options:
          grouping: {  }
          row_class: ''
          default_row_class: true
          columns:
            views_bulk_operations_bulk_form: views_bulk_operations_bulk_form
            title: title
            bundle: bundle
            operations: operations
          default: bundle
          info:
            views_bulk_operations_bulk_form:
              align: ''
              separator: ''
              empty_column: false
              responsive: ''
            title:
              sortable: true
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: false
              responsive: ''
            bundle:
              sortable: true
              default_sort_order: asc
              align: ''
              separator: ''
              empty_column: false
              responsive: ''
            operations:
              align: ''
              separator: ''
              empty_column: false
              responsive: ''
          override: true
          sticky: false
          summary: ''
          empty_table: false
          caption: ''
          description: ''
      row:
        type: fields
      query:
        type: views_query
        options:
          query_comment: ''
          disable_sql_rewrite: false
          distinct: false
          replica: false
          query_tags: {  }
      relationships: {  }
      header: {  }
      footer: {  }
      display_extenders: {  }
    cache_metadata:
      max-age: 0
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - url.query_args
        - user.permissions
      tags: {  }
  page_1:
    id: page_1
    display_title: Page
    display_plugin: page
    position: 1
    display_options:
      display_extenders:
        metatag_display_extender:
          metatags: {  }
          tokenize: false
      path: admin/content/directories/facets
    cache_metadata:
      max-age: 0
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - url.query_args
        - user.permissions
      tags: {  }

```
