### ISSUE TITLE
Search index fields for node title & title sort are not the same type

### ISSUE THREAD

**Issue by joachim-n** [localgovdrupal/localgov_directories#405]
We have:

```
    $field = new SearchIndexField($index, Constants::TITLE_SORT_FIELD);
    $field->setLabel('Title (sort)');
    $field->setDataSourceId('entity:node');
    $field->setPropertyPath(Constants::TITLE_SORT_FIELD);
    $field->setType('string');
```

but also:

```
  title:
    label: Title
    datasource_id: 'entity:node'
    property_path: title
    boost: 5.0
    type: text
```

Should this discrepancy be fixed in Finders, or does it have a reason?
