### ISSUE TITLE
Item count above Directory entry listing

### ISSUE THREAD

**Issue by Adnan-cds** [localgovdrupal/localgov_directories#58]
In the BHCC codebase, the Directory listing displays an item count above the listing.  Example text from an [example URL](http://brightonhove3stg.prod.acquia-sites.com/directories/public-toilets): *Displaying 1 - 10 of 92 results*

We are missing this small feature in LocalGov as you can see in the [LocalGov Croydon site](https://new.croydon.gov.uk/schools-and-education/schools/find-school-near-you/secondary-schools).  It will be good to have it back.

FAO @finnlewis @willguv @andybroomfield

**Comment by andybroomfield** [comment]
Is localgov directories still a view? In that case its just a case of adding it as a view summary. We just used the default one in views.

**Comment by andybroomfield** [comment]
This can be added to the view as a results summary. Easy enough to add, though as its config there is the update question.

<img width="961" alt="Screenshot 2024-09-18 at 12 02 11 PM" src="https://github.com/user-attachments/assets/024cab69-372f-48c8-aca1-9e1cb90fd88d">

<img width="830" alt="Screenshot 2024-09-18 at 12 01 58 PM" src="https://github.com/user-attachments/assets/816da97a-fc78-4be3-9c77-0889897d1301">

```yaml
      footer:
        result:
          id: result
          table: views
          field: result
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: result
          empty: false
          content: 'Displaying @start - @end of @total results'
```

**Comment by andybroomfield** [comment]
Heres the full view config
```yaml
uuid: 2610bea9-8639-4e19-a5fd-6d353c5cf724
langcode: en
status: true
dependencies:
  config:
    - field.storage.geo_entity.location
    - field.storage.node.body
    - search_api.index.localgov_directories_index_default
  module:
    - geo_entity
    - geofield
    - leaflet_views
    - search_api
    - search_api_location_views
    - text
_core:
  default_config_hash: eN4zGMUiShe29x5JZoARS7Vsl_Jqsy9sCDbE13bH6pY
id: localgov_directory_channel
label: 'Directory channel'
module: views
description: 'View to embed to display a particular directory channel'
tag: ''
base_table: search_api_index_localgov_directories_index_default
base_field: search_api_id
display:
  default:
    id: default
    display_title: Master
    display_plugin: default
    position: 0
    display_options:
      fields:
        localgov_directory_facets_select:
          id: localgov_directory_facets_select
          table: search_api_index_localgov_directories_index_default
          field: localgov_directory_facets_select
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: null
          entity_field: null
          plugin_id: search_api_field
          label: ''
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: true
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: target_id
          type: entity_reference_label
          settings: {  }
          group_column: target_id
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          field_rendering: true
          fallback_handler: search_api_entity
          fallback_options:
            link_to_item: false
            use_highlighting: false
            multi_type: separator
            multi_separator: ', '
            display_methods: {  }
      pager:
        type: mini
        options:
          offset: 0
          pagination_heading_level: h4
          items_per_page: 10
          total_pages: null
          id: 0
          tags:
            next: ››
            previous: ‹‹
          expose:
            items_per_page: false
            items_per_page_label: 'Items per page'
            items_per_page_options: '5, 10, 25, 50'
            items_per_page_options_all: false
            items_per_page_options_all_label: '- All -'
            offset: false
            offset_label: Offset
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: false
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: true
          sort_asc_label: Asc
          sort_desc_label: Desc
      access:
        type: none
        options: {  }
      cache:
        type: search_api_none
        options: {  }
      empty: {  }
      sorts:
        search_api_relevance:
          id: search_api_relevance
          table: search_api_index_localgov_directories_index_default
          field: search_api_relevance
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: search_api
          order: DESC
          expose:
            label: ''
          exposed: false
        localgov_directory_title_sort:
          id: localgov_directory_title_sort
          table: search_api_index_localgov_directories_index_default
          field: localgov_directory_title_sort
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: search_api
          order: ASC
          expose:
            label: ''
          exposed: false
      arguments:
        localgov_directory_channels:
          id: localgov_directory_channels
          table: search_api_index_localgov_directories_index_default
          field: localgov_directory_channels
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: search_api
          default_action: 'not found'
          exception:
            value: all
            title_enable: false
            title: All
          title_enable: false
          title: ''
          default_argument_type: fixed
          default_argument_options:
            argument: ''
          summary_options: {  }
          summary:
            sort_order: asc
            number_of_records: 0
            format: default_summary
          specify_validation: false
          validate:
            type: none
            fail: 'not found'
          validate_options: {  }
          break_phrase: false
          not: false
      filters:
        search_api_fulltext:
          id: search_api_fulltext
          table: search_api_index_localgov_directories_index_default
          field: search_api_fulltext
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: search_api_fulltext
          operator: or
          value: ''
          group: 1
          exposed: true
          expose:
            operator_id: search_api_fulltext_op
            label: Search
            description: ''
            use_operator: false
            operator: search_api_fulltext_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: search_api_fulltext
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
            placeholder: ''
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          parse_mode: terms
          min_length: null
          fields: {  }
      style:
        type: default
        options:
          grouping: {  }
          row_class: ''
          default_row_class: true
          uses_fields: false
      row:
        type: search_api
        options:
          view_modes:
            'entity:node':
              localgov_directories_page: teaser
              localgov_directories_venue: teaser
              localgov_directory_page: search_result
      query:
        type: search_api_query
        options:
          bypass_access: false
          skip_access: false
          preserve_facet_query_args: false
      relationships: {  }
      header: {  }
      footer:
        result:
          id: result
          table: views
          field: result
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: result
          empty: false
          content: 'Displaying @start - @end of @total results'
      display_extenders: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_interface'
        - url
        - url.query_args
        - 'user.node_grants:view'
      tags:
        - 'config:search_api.index.localgov_directories_index_default'
        - 'search_api_list:localgov_directories_index_default'
  embed_map:
    id: embed_map
    display_title: 'Embed: map'
    display_plugin: embed
    position: 2
    display_options:
      fields:
        title:
          id: title
          table: search_api_datasource_localgov_directories_index_default_entity_node
          field: title
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: node
          plugin_id: search_api_field
          label: ''
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: div
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: string
          settings:
            link_to_entity: true
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          field_rendering: true
          fallback_handler: search_api
          fallback_options:
            link_to_item: false
            use_highlighting: false
            multi_type: separator
            multi_separator: ', '
        location:
          id: location
          table: search_api_entity_geo_entity
          field: location
          relationship: localgov_location
          group_type: group
          admin_label: ''
          entity_type: geo_entity
          plugin_id: search_api_field
          label: ''
          exclude: true
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: geofield_default
          settings:
            output_format: json
            output_escape: true
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          field_rendering: true
          fallback_handler: search_api
          fallback_options:
            link_to_item: false
            use_highlighting: false
            multi_type: separator
            multi_separator: ', '
        search_api_rendered_item:
          id: search_api_rendered_item
          table: search_api_index_localgov_directories_index_default
          field: search_api_rendered_item
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: search_api_rendered_item
          label: ''
          exclude: true
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          view_modes:
            'entity:node':
              localgov_directories_page: teaser
              localgov_directories_venue: teaser
              localgov_directory_promo_page: default
      pager:
        type: none
        options:
          offset: 0
      empty: {  }
      filters:
        search_api_fulltext:
          id: search_api_fulltext
          table: search_api_index_localgov_directories_index_default
          field: search_api_fulltext
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: search_api_fulltext
          operator: or
          value: ''
          group: 1
          exposed: true
          expose:
            operator_id: search_api_fulltext_op
            label: Search
            description: ''
            use_operator: false
            operator: search_api_fulltext_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: search_api_fulltext
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
            placeholder: ''
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          parse_mode: terms
          min_length: null
          fields: {  }
        localgov_location:
          id: localgov_location
          table: search_api_index_localgov_directories_index_default
          field: localgov_location
          relationship: none
          group_type: group
          admin_label: Proximity
          plugin_id: search_api_location
          operator: '<'
          value:
            value: ''
            distance:
              from: '-'
              to: '-'
          group: 1
          exposed: true
          expose:
            operator_id: localgov_location_op
            label: Location
            description: ''
            use_operator: false
            operator: localgov_location_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: localgov_location
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
              content_editor: '0'
              administrator: '0'
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          plugin: geocode
          plugin-geocode:
            plugins:
              localgov_default_osm:
                checked: '1'
                weight: '0'
            radius_type: select
            radius_options: "- -\r\n1 1/2 mile\r\n2 1 mile\r\n3 2 miles\r\n5 3 miles\r\n8 5 miles\r\n16 10 miles"
            radius_units: km
          plugin-geocode_map:
            radius_border_color: ''
            radius_border_weight: ''
            radius_background_color: ''
            radius_background_transparency: ''
            marker_image: ''
          plugin-raw:
            radius_type: select
            radius_options: "- -\r\n1 1/2 mile\r\n2 1 mile\r\n3 2 miles\r\n5 3 miles\r\n8 5 miles\r\n16 10 miles"
            radius_units: km
      filter_groups:
        operator: AND
        groups:
          1: AND
      style:
        type: leaflet_map
        options:
          grouping: {  }
          data_source:
            location: location
          entity_source: __base_table
          entity_source_submit: 'Update Entity Source'
          name_field: title
          leaflet_tooltip:
            value: ''
            options: '{"permanent":false,"direction":"center"}'
          leaflet_popup:
            value: '#rendered_view_fields'
            options: '{"maxWidth":"300","minWidth":"50","autoPan":true}'
          leaflet_map: 'OSM Mapnik'
          height: '400'
          height_unit: px
          hide_empty_map: true
          disable_wheel: false
          gesture_handling: false
          reset_map:
            control: false
            options: '{"position":"topleft","title":"Reset View"}'
          map_scale:
            control: false
            options: '{"position":"bottomright","maxWidth":100,"metric":true,"imperial":false,"updateWhenIdle":false}'
          locate:
            control: false
            options: '{"position":"topright","setView":"untilPanOrZoom","returnToPrevBounds":true,"keepCurrentZoomLevel":true,"strings":{"title":"Locate my position"}}'
            automatic: false
          map_position:
            force: false
            center:
              lat: 0.0
              lon: 0.0
            zoomControlPosition: topleft
            zoom: 12
            minZoom: 1
            maxZoom: 18
            zoomFiner: 0
          weight: ''
          icon:
            iconType: marker
            iconUrl: ''
            shadowUrl: ''
            className: ''
            iconSize:
              x: ''
              'y': ''
            iconAnchor:
              x: ''
              'y': ''
            shadowSize:
              x: ''
              'y': ''
            shadowAnchor:
              x: ''
              'y': ''
            popupAnchor:
              x: ''
              'y': ''
            html: '<div></div>'
            html_class: leaflet-map-divicon
            circle_marker_options: '{"radius":100,"color":"red","fillColor":"#f03","fillOpacity":0.5}'
          fullscreen:
            control: true
            options: '{"position":"topleft","pseudoFullscreen":false}'
          path: '{"color":"#3388ff","opacity":"1.0","stroke":true,"weight":3,"fill":"depends","fillColor":"*","fillOpacity":"0.2"}'
          geocoder:
            control: false
            settings:
              autocomplete:
                placeholder: 'Search Address'
                title: 'Search an Address on the Map'
              position: topright
              input_size: 25
              providers:
                file:
                  weight: '0'
                  checked: 0
                gpx_file:
                  weight: '0'
                  checked: 0
                geojson_file:
                  weight: '0'
                  checked: 0
                kml_file:
                  weight: '0'
                  checked: 0
                geo_entity_osm:
                  weight: '0'
                  checked: 0
                geo_entity_demo_photon:
                  weight: '0'
                  checked: 0
              min_terms: 4
              delay: 800
              zoom: 16
              popup: false
              options: ''
          map_lazy_load:
            lazy_load: false
      row:
        type: fields
        options:
          default_field_elements: true
          inline:
            title: title
          separator: ''
          hide_empty: false
      defaults:
        empty: false
        pager: false
        style: false
        row: false
        relationships: false
        fields: false
        filters: false
        filter_groups: false
        footer: false
      relationships:
        localgov_location:
          id: localgov_location
          table: search_api_datasource_localgov_directories_index_default_entity_node
          field: localgov_location
          relationship: none
          group_type: group
          admin_label: 'Location: Geo'
          entity_type: node
          plugin_id: search_api
          required: false
          skip_access: false
      display_description: ''
      footer: {  }
      display_extenders: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - 'user.node_grants:view'
      tags:
        - 'config:field.storage.geo_entity.location'
        - 'config:search_api.index.localgov_directories_index_default'
        - 'search_api_list:localgov_directories_index_default'
  node_embed:
    id: node_embed
    display_title: Embed
    display_plugin: embed
    position: 1
    display_options:
      cache:
        type: search_api_none
      defaults:
        cache: false
        footer: true
      display_extenders: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_interface'
        - url
        - url.query_args
        - 'user.node_grants:view'
      tags:
        - 'config:search_api.index.localgov_directories_index_default'
        - 'search_api_list:localgov_directories_index_default'
  node_embed_for_proximity_search:
    id: node_embed_for_proximity_search
    display_title: 'Embed: Proximity search'
    display_plugin: embed
    position: 1
    display_options:
      fields:
        title:
          id: title
          table: search_api_datasource_localgov_directories_index_default_entity_node
          field: title
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: node
          plugin_id: search_api_field
          label: ''
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: h2
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: string
          settings:
            link_to_entity: false
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          field_rendering: false
          fallback_handler: search_api
          fallback_options:
            link_to_item: true
            use_highlighting: false
            multi_type: separator
            multi_separator: ', '
        body:
          id: body
          table: search_api_datasource_localgov_directories_index_default_entity_node
          field: body
          relationship: none
          group_type: group
          admin_label: ''
          entity_type: node
          plugin_id: search_api_field
          label: ''
          exclude: false
          alter:
            alter_text: false
            text: ''
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          click_sort_column: value
          type: text_summary_or_trimmed
          settings:
            trim_length: 600
          group_column: value
          group_columns: {  }
          group_rows: true
          delta_limit: 0
          delta_offset: 0
          delta_reversed: false
          delta_first_last: false
          multi_type: separator
          separator: ', '
          field_api_classes: false
          field_rendering: true
          fallback_handler: search_api
          fallback_options:
            link_to_item: false
            use_highlighting: false
            multi_type: separator
            multi_separator: ', '
        localgov_location_distance:
          id: localgov_location_distance
          table: search_api_index_localgov_directories_index_default
          field: localgov_location_distance
          relationship: none
          group_type: group
          admin_label: Proximity
          plugin_id: search_api_numeric
          label: ''
          exclude: false
          alter:
            alter_text: true
            text: '{{ (localgov_location_distance / 1.609) | round(1) }} miles'
            make_link: false
            path: ''
            absolute: false
            external: false
            replace_spaces: false
            path_case: none
            trim_whitespace: false
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: false
            max_length: 0
            word_boundary: true
            ellipsis: true
            more_link: false
            more_link_text: ''
            more_link_path: ''
            strip_tags: false
            trim: false
            preserve_tags: ''
            html: false
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: false
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: true
          empty: ''
          hide_empty: false
          empty_zero: false
          hide_alter_empty: true
          set_precision: false
          precision: 0
          decimal: .
          separator: ''
          format_plural: false
          format_plural_string: !!binary Aw==
          prefix: ''
          suffix: ''
          link_to_item: false
          use_highlighting: false
          multi_type: separator
          multi_separator: ', '
          format_plural_values: {  }
      cache:
        type: search_api_none
      sorts:
        localgov_location_distance:
          id: localgov_location_distance
          table: search_api_index_localgov_directories_index_default
          field: localgov_location_distance
          relationship: none
          group_type: group
          admin_label: Proximity
          plugin_id: search_api_location_distance
          order: ASC
          expose:
            label: ''
            field_identifier: ''
          exposed: false
        search_api_relevance:
          id: search_api_relevance
          table: search_api_index_localgov_directories_index_default
          field: search_api_relevance
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: search_api
          order: DESC
          expose:
            label: ''
            field_identifier: search_api_relevance
          exposed: false
        localgov_directory_title_sort:
          id: localgov_directory_title_sort
          table: search_api_index_localgov_directories_index_default
          field: localgov_directory_title_sort
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: search_api
          order: ASC
          expose:
            label: ''
            field_identifier: localgov_directory_title_sort
          exposed: false
      filters:
        search_api_fulltext:
          id: search_api_fulltext
          table: search_api_index_localgov_directories_index_default
          field: search_api_fulltext
          relationship: none
          group_type: group
          admin_label: ''
          plugin_id: search_api_fulltext
          operator: or
          value: ''
          group: 1
          exposed: true
          expose:
            operator_id: search_api_fulltext_op
            label: Search
            description: ''
            use_operator: false
            operator: search_api_fulltext_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: search_api_fulltext
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
            placeholder: ''
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          parse_mode: terms
          min_length: null
          fields: {  }
        localgov_location:
          id: localgov_location
          table: search_api_index_localgov_directories_index_default
          field: localgov_location
          relationship: none
          group_type: group
          admin_label: Proximity
          plugin_id: search_api_location
          operator: '<'
          value:
            value: ''
            distance:
              from: '-'
              to: '-'
          group: 1
          exposed: true
          expose:
            operator_id: localgov_location_op
            label: Location
            description: 'Proximity from a given location.'
            use_operator: false
            operator: localgov_location_op
            operator_limit_selection: false
            operator_list: {  }
            identifier: localgov_location
            required: false
            remember: false
            multiple: false
            remember_roles:
              authenticated: authenticated
              anonymous: '0'
              content_editor: '0'
              administrator: '0'
          is_grouped: false
          group_info:
            label: ''
            description: ''
            identifier: ''
            optional: true
            widget: select
            multiple: false
            remember: false
            default_group: All
            default_group_multiple: {  }
            group_items: {  }
          plugin: geocode
          plugin-geocode:
            plugins:
              localgov_default_osm:
                checked: '1'
                weight: '0'
            radius_type: select
            radius_options: "- -\r\n1 1/2 mile\r\n2 1 mile\r\n3 2 miles\r\n5 3 miles\r\n8 5 miles\r\n16 10 miles"
            radius_units: km
          plugin-geocode_map:
            radius_border_color: ''
            radius_border_weight: ''
            radius_background_color: ''
            radius_background_transparency: ''
            marker_image: ''
          plugin-raw:
            radius_type: select
            radius_options: "- -\r\n1 1/2 mile\r\n2 1 mile\r\n3 2 miles\r\n5 3 miles\r\n8 5 miles\r\n16 10 miles"
            radius_units: km
      filter_groups:
        operator: AND
        groups:
          1: AND
      style:
        type: default
        options:
          grouping: {  }
          row_class: ''
          default_row_class: true
          uses_fields: false
      row:
        type: fields
        options:
          default_field_elements: true
          inline: {  }
          separator: ''
          hide_empty: false
      defaults:
        cache: false
        style: false
        row: false
        fields: false
        sorts: false
        filters: false
        filter_groups: false
      display_description: 'Proximity search for Directory entries'
      display_comment: 'Solr''s distance calculation uses Kilometer as the unit by default.  The "Proximity" field uses the "Rewrite results" settings to display such distances in miles.  1 Mile is 1609 meter.'
      display_extenders: {  }
    cache_metadata:
      max-age: -1
      contexts:
        - 'languages:language_content'
        - 'languages:language_interface'
        - url
        - url.query_args
        - 'user.node_grants:view'
      tags:
        - 'config:field.storage.node.body'
        - 'config:search_api.index.localgov_directories_index_default'
        - 'search_api_list:localgov_directories_index_default'
```
